{% set name = "pytest-loguru" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 0d9e4e72ae9bfd92f774c666e7353766af11b0b78edd59c290e89be116050f03

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling
    - hatch-vcs
    - wheel
  run:
    - python >=3.8
    - pytest >=7.0.0
    - loguru >=0.7.2

test:
  imports:
    - pytest_loguru
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/mcarans/pytest-loguru
  summary: "A pytest plugin to add support for loguru to pytest's caplog fixture"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://loguru.readthedocs.io/en/stable/index.html
  dev_url: https://github.com/mcarans/pytest-loguru

extra:
  recipe-maintainers:
    - mcarans
    - Zeitsperre
