{% set name = "pytest-loguru" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2248a2bdd4d3b396b06f5513c7208280b67d4dab27555aa65c310a82c2942dbe

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
    - wheel
  run:
    - python >={{ python_min }}
    - pytest >=7.0.0
    - loguru >=0.7.2

test:
  imports:
    - pytest_loguru
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/mcarans/pytest-loguru
  summary: "A pytest plugin to add support for loguru to pytest's caplog fixture"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://loguru.readthedocs.io/en/stable/index.html
  dev_url: https://github.com/mcarans/pytest-loguru

extra:
  recipe-maintainers:
    - mcarans
    - Zeitsperre
