{% set name = "pytest-loguru" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9bf2d5e95d9bba88ae5aa78e81ed835f96cbc092dbc5bdc929a0882f04516eaa

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools >=45
    - setuptools_scm >=6.2
    - wheel
  run:
    - python >=3.6
    - pytest
    - loguru

test:
  imports:
    - pytest_loguru
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/mcarans/pytest-loguru
  summary: "A pytest plugin to add support for loguru to pytest's caplog fixture"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://loguru.readthedocs.io/en/stable/index.html
  dev_url: https://github.com/mcarans/pytest-loguru

extra:
  recipe-maintainers:
    - mcarans
    - Zeitsperre
